flag_management:
  individual_flags:
    - name: python
      paths:
        - anqa/
    - name: rust
      paths:
        - desktop/

component_management:
  individual_components:
    - component_id: python
      name: python
      paths:
        - anqa/**
    - component_id: rust
      name: rust
      paths:
        - desktop/**
