"""Generate companion skills that steer agents to use persona MCP servers."""

from __future__ import annotations

import re
from pathlib import Path

from ..models import JsonObject

# Frontmatter marker so scanners can hide these from user skill pickers.
GROKET_MCP_COMPANION_MARKER = "groket-mcp-companion"


def companion_skill_name(server_id: str) -> str:
    """Skill dir name for an MCP server id (stable, filesystem-safe)."""
    sid = re.sub(r"[^a-zA-Z0-9._-]+", "-", (server_id or "mcp").strip().lower()).strip("-")
    sid = sid[:40] or "mcp"
    return f"use-{sid}-mcp"


def is_mcp_companion_skill_name(name: str) -> bool:
    """True for auto-generated ``use-<server>-mcp`` companion skill dir names."""
    n = (name or "").strip().lower()
    return bool(n) and n.startswith("use-") and n.endswith("-mcp") and len(n) > len("use--mcp")


def is_mcp_companion_skill_md(skill_md: Path) -> bool:
    """True if SKILL.md was written by :func:`write_mcp_companion_skill`."""
    try:
        head = skill_md.read_text(encoding="utf-8", errors="replace")[:800]
    except OSError:
        return False
    if GROKET_MCP_COMPANION_MARKER in head:
        return True
    return False


def is_implicit_mcp_companion_skill(name: str, skill_md: Path | None = None) -> bool:
    """Hide from skill pickers: naming convention and/or frontmatter marker."""
    if is_mcp_companion_skill_name(name):
        return True
    if skill_md is not None and skill_md.is_file() and is_mcp_companion_skill_md(skill_md):
        return True
    return False


def render_mcp_companion_skill_md(defn: JsonObject) -> str:
    """SKILL.md body: when/how to use this MCP vs terminal/generic tools."""
    sid = str(defn.get("id") or "mcp").strip() or "mcp"
    title = str(defn.get("title") or sid)
    desc = str(defn.get("description") or "").strip()
    transport = str(defn.get("transport") or "http").lower()
    url = str(defn.get("url") or "").strip()
    command = str(defn.get("command") or "").strip()
    reg = str(defn.get("registry_name") or "").strip()
    needs = defn.get("needs_env") or []
    if not isinstance(needs, list):
        needs = []

    tool_prefix = f"{sid}__"
    # Don't use registry name for domain keywords (often `io.github.*` false-positives).
    domain_hints = _domain_hints(sid, title, desc, "")

    endpoint_bits = []
    if transport in ("http", "sse") and url:
        endpoint_bits.append(f"Remote MCP (`{transport}`): `{url}`")
    elif transport == "stdio" and command:
        args = defn.get("args") or []
        args_s = " ".join(str(a) for a in args) if isinstance(args, list) else ""
        endpoint_bits.append(f"stdio MCP: `{command} {args_s}`".strip())
    endpoint_line = (
        endpoint_bits[0] if endpoint_bits else f"Configured as persona MCP server id `{sid}`."
    )

    env_note = ""
    if needs:
        env_note = (
            "\n\n## Credentials / env\n\n"
            "This server may require env vars on the persona (already injected into the container when set):\n"
            + "\n".join(f"- `{k}`" for k in needs)
            + "\n\nIf tools fail with auth errors, do not invent tokens; report the failure.\n"
        )

    return f"""---
name: {companion_skill_name(sid)}
# Implicit skill generated by groket when an MCP server is configured on a persona.
# Not shown in skill pickers (see is_implicit_mcp_companion_skill).
x-groket: {GROKET_MCP_COMPANION_MARKER}
description: >
  Prefer the {title} MCP server (id `{sid}`) for tasks in its domain. Use search_tool/use_tool
  with tools prefixed `{tool_prefix}` instead of shell/curl/ad-hoc APIs when this MCP can do the job.
  Use when the user asks about {domain_hints}.
when-to-use: >
  Music/metadata/API/integration tasks that match this server; any request that should use
  MCP tools for `{sid}` rather than terminal workarounds.
disable-model-invocation: false
---

# Use {title} MCP (`{sid}`)

This persona has the **{title}** MCP server enabled. Grok exposes its tools via the integration
tooling (`search_tool` / `use_tool`), namespaced as **`{tool_prefix}<tool_name>`**.

{endpoint_line}
{f"Registry: `{reg}`." if reg else ""}
{f"Server purpose: {desc}" if desc else ""}

## Mandatory tool preference

1. **Discover** available tools: call `search_tool` with keywords from the task (e.g. the service name, resource type).
2. **Prefer MCP** over `run_terminal_command` / `curl` / inventing API access when a matching `{tool_prefix}*` tool exists.
3. **Call tools** with `use_tool` and the fully-qualified name from `search_tool` (always includes the `{sid}__` prefix).
4. **Do not** reimplement the integration via shell scripts, scraped HTML, or guessed endpoints if MCP succeeds or is clearly available.
5. If MCP fails (timeout, auth, missing tool), say so clearly; only then fall back to other approaches.

## When this skill applies

Use this skill whenever the task involves **{domain_hints}**, or the user explicitly asks to use MCP / this integration.

## Anti-patterns (avoid)

- Using terminal/HTTP to call the same backend the MCP already wraps.
- Ignoring `search_tool` results and guessing tool names without the `{sid}__` prefix.
- Claiming success without having called the MCP tool when one was appropriate.
{env_note}
## Quick recipe

1. `search_tool` — query: `{sid}` or domain keywords from the user request.
2. Pick the best `{tool_prefix}…` tool from results.
3. `use_tool` with that name and required arguments.
4. Summarize results with evidence (tool output), not speculation.
"""


def _domain_hints(sid: str, title: str, desc: str, reg: str = "") -> str:
    blob = f"{sid} {title} {desc}".lower()
    _ = reg
    hints: list[str] = []
    mapping = [
        (
            ("music", "musicbrainz", "release", "artist", "recording"),
            "music metadata / MusicBrainz / releases / artists",
        ),
        (("slack", "message", "channel"), "Slack messages / channels / workspace"),
        (("github", "pull", "issue", "repo"), "GitHub issues / PRs / repositories"),
        (("linear", "ticket", "issue"), "Linear issues / projects"),
        (("sentry", "error", "exception"), "Sentry errors / issues"),
        (("notion", "page", "wiki"), "Notion pages / docs"),
        (("postgres", "sql", "database", "db"), "database queries / schema"),
        (("browser", "playwright", "web"), "browser / web automation"),
    ]
    for keys, phrase in mapping:
        if any(k in blob for k in keys):
            hints.append(phrase)
    if not hints:
        hints.append(f"`{title}` / `{sid}` domain tasks")
    return "; ".join(hints[:3])


def write_mcp_companion_skill(
    work_dir: Path,
    defn: JsonObject,
    *,
    overwrite: bool = True,
) -> tuple[str, Path] | None:
    """Write companion skill under work_dir/skills/<name>/SKILL.md. Returns (skill_name, path) or None."""
    sid = str(defn.get("id") or "").strip()
    if not sid:
        return None
    name = companion_skill_name(sid)
    root = Path(work_dir).expanduser() / "skills" / name
    root.mkdir(parents=True, exist_ok=True)
    target = root / "SKILL.md"
    if target.is_file() and not overwrite:
        return name, target
    target.write_text(render_mcp_companion_skill_md(defn), encoding="utf-8")
    return name, target
