"""Type stubs for the compiled ``anqa._scan`` module."""

def keep_updates_line(line: bytes) -> bool: ...
def filter_updates(data: bytes) -> list[bytes]: ...
def find_sessions(root: str) -> list[str]: ...
def looks_like_session_dir(path: str) -> bool: ...
