
# Optional multiline initial commands (copied as a script; executed in entrypoint)
COPY setup.sh /groket-setup.sh
RUN chmod +x /groket-setup.sh

COPY groket-share-once.py /groket-share-once.py
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /groket-share-once.py

ENTRYPOINT ["/entrypoint.sh"]
